#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage.
if (( $+commands[fortune] )); then
  fortune="fortune -a"
  if (( $+commands[cowsay] )); then
    sort="sort"
    if (( $+commands[gsort] )); then
      sort="gsort"
    fi
    fortune="$fortune | cowsay -f \"$(ls /opt/local/share/cowsay/cows/ | $sort -R | head -1)\""
  fi
  if (( $+commands[lolcat] )); then
    fortune="$fortune | lolcat"
  fi
  eval $fortune
  print
fi


### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
