#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# http://www.network-theory.co.uk/docs/gccintro/gccintro_23.html
CPLUS_INCLUDE_PATH=/usr/X11R6/include
export CPLUS_INCLUDE_PATH
