#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Key-bindings
# bind UP and DOWN arrow keys
#zmodload zsh/terminfo
bindkey "$key_info[Up]" history-beginning-search-backward
bindkey "$key_info[Down]" history-beginning-search-forward

# Fix keys for iTerm
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

# bind P and N for EMACS mode
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

# bind k and j for VI mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

alias ccat=/opt/local/bin/pygmentize-2.7 -g
# Syntax highlighting
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=fg=yellow
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=fg=yellow
ZSH_HIGHLIGHT_STYLES[path]=fg=blue
ZSH_HIGHLIGHT_STYLES[globbing]=fg=cyan

# be verbose, i.e. show descriptions
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'

# group by tag names
zstyle ':completion:*' group-name ''

# Customize to your needs...
# Load RVM function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# XQuartz libs are not in the usual place.
CPLUS_INCLUDE_PATH=/usr/X11R6/include; export CPLUS_INCLUDE_PATH
export EDITOR=vim
export VISUAL=vim
export VIDIR_EDITOR_ARGS='-c :set nolist | :set ft=vidir-ls'
[[ -s "$HOME/.dircolors" ]] && eval $( gdircolors -b $HOME/.dircolors )

function tmux_create_or_reattach() { tmux has-session -t $1 && tmux attach -t $1 || tmux -u -L $1; }

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
